services:
  - type: web
    name: your-app
    runtime: node
    buildCommand: |
      pip install -r api/requirements.txt && 
      npm install && 
      npm run build
    startCommand: |
      python api/index.py & 
      npm run start
    envVars:
      - key: FLASK_PORT
        value: "5328"
      - key: NEXT_PUBLIC_API_URL
        value: "/api"