services:
  - type: web
    name: next-flask-app
    runtime: node
    buildCommand: |
      sudo apt-get update && 
      sudo apt-get install -y openjdk-17-jre && 
      python -m venv venv && 
      . venv/bin/activate && 
      pip install --upgrade pip && 
      pip install -r api/requirements.txt && 
      npm install && 
      npm run build
    startCommand: . venv/bin/activate && npm run start-production
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_PORT
        value: "5328"
      - key: NEXT_PUBLIC_API_URL
        value: "/api"