services:
  - type: web
    name: next-flask-app
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_PORT
        value: "5328"
      - key: NEXT_PUBLIC_API_URL
        value: "/api"