services:
  - type: web
    name: next-flask-app
    runtime: node
    buildCommand: |
      npm run install-deps &&
      npm run build
    startCommand: npm run start-production
    envVars:
      - key: FLASK_PORT
        value: "5328"
      - key: NEXT_PUBLIC_API_URL
        value: "/api"